name: "bluebell"
mode: "dev"
port: 8080
version: "v0.1.4"
start_time: "2020-07-01"
machine_id: 1

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.1.4"
  port: 13306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "192.168.1.4"
  port: 16379
  password: "123456"
  db: 0
  pool_size: 100